name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigend-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Board
          column: In Progress
          repo-token: ${{ secrets.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 }}
